export { HomeAboutSection } from './about/ui/home-about-section'
export { HomeContactSection } from './contact/ui/home-contact-section'
export { HomeHeroSection } from './hero/ui/home-hero-section'
export { HomeProjectsSection } from './projects/ui/home-projects-section'
export { HomeServicesSection } from './services/ui/home-services-section'
